
services:
  aliyunddns:
    image: aliyunddns:latest
    container_name: aliyunddns
    restart: unless-stopped
    volumes:
      - "./config.cfg:/opt/aliyunddns/aliyun-ddns/config.cfg:ro"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://baidu.com | grep -q '200 OK' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 999999999
      start_period: 30s
